package com.cvp.reas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class REASDatos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("tipoExpediente")
	private java.lang.String tipoExpediente;
	@org.kie.api.definition.type.Label("idExpediente")
	private java.lang.String idExpediente;
	@org.kie.api.definition.type.Label("fechaExpediente")
	private java.lang.String fechaExpediente;
	@org.kie.api.definition.type.Label("nombreDocumentoRecomendacion")
	private java.lang.String nombreDocumentoRecomendacion;
	@org.kie.api.definition.type.Label("fechaDocumentoRecomendacion")
	private java.lang.String fechaDocumentoRecomendacion;
	@org.kie.api.definition.type.Label("nombreAdenda")
	private java.lang.String nombreAdenda;
	@org.kie.api.definition.type.Label("fechaAdenda")
	private java.lang.String fechaAdenda;
	@org.kie.api.definition.type.Label("numeroRadicadoRecomendacion")
	private java.lang.String numeroRadicadoRecomendacion;
	@org.kie.api.definition.type.Label("fechaRadicadoRecomendacion")
	private java.lang.String fechaRadicadoRecomendacion;
	@org.kie.api.definition.type.Label("remitente")
	private java.lang.String remitente;
	@org.kie.api.definition.type.Label("proyecto")
	private java.lang.String proyecto;

	@org.kie.api.definition.type.Label(value = "tipoAmenaza")
	private java.lang.String tipoAmenaza;

	public REASDatos() {
	}

	public java.lang.String getTipoExpediente() {
		return this.tipoExpediente;
	}

	public void setTipoExpediente(java.lang.String tipoExpediente) {
		this.tipoExpediente = tipoExpediente;
	}

	public java.lang.String getIdExpediente() {
		return this.idExpediente;
	}

	public void setIdExpediente(java.lang.String idExpediente) {
		this.idExpediente = idExpediente;
	}

	public java.lang.String getFechaExpediente() {
		return this.fechaExpediente;
	}

	public void setFechaExpediente(java.lang.String fechaExpediente) {
		this.fechaExpediente = fechaExpediente;
	}

	public java.lang.String getNombreDocumentoRecomendacion() {
		return this.nombreDocumentoRecomendacion;
	}

	public void setNombreDocumentoRecomendacion(
			java.lang.String nombreDocumentoRecomendacion) {
		this.nombreDocumentoRecomendacion = nombreDocumentoRecomendacion;
	}

	public java.lang.String getFechaDocumentoRecomendacion() {
		return this.fechaDocumentoRecomendacion;
	}

	public void setFechaDocumentoRecomendacion(
			java.lang.String fechaDocumentoRecomendacion) {
		this.fechaDocumentoRecomendacion = fechaDocumentoRecomendacion;
	}

	public java.lang.String getNombreAdenda() {
		return this.nombreAdenda;
	}

	public void setNombreAdenda(java.lang.String nombreAdenda) {
		this.nombreAdenda = nombreAdenda;
	}

	public java.lang.String getFechaAdenda() {
		return this.fechaAdenda;
	}

	public void setFechaAdenda(java.lang.String fechaAdenda) {
		this.fechaAdenda = fechaAdenda;
	}

	public java.lang.String getNumeroRadicadoRecomendacion() {
		return this.numeroRadicadoRecomendacion;
	}

	public void setNumeroRadicadoRecomendacion(
			java.lang.String numeroRadicadoRecomendacion) {
		this.numeroRadicadoRecomendacion = numeroRadicadoRecomendacion;
	}

	public java.lang.String getFechaRadicadoRecomendacion() {
		return this.fechaRadicadoRecomendacion;
	}

	public void setFechaRadicadoRecomendacion(
			java.lang.String fechaRadicadoRecomendacion) {
		this.fechaRadicadoRecomendacion = fechaRadicadoRecomendacion;
	}

	public java.lang.String getRemitente() {
		return this.remitente;
	}

	public void setRemitente(java.lang.String remitente) {
		this.remitente = remitente;
	}

	public java.lang.String getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(java.lang.String proyecto) {
		this.proyecto = proyecto;
	}

	public java.lang.String getTipoAmenaza() {
		return this.tipoAmenaza;
	}

	public void setTipoAmenaza(java.lang.String tipoAmenaza) {
		this.tipoAmenaza = tipoAmenaza;
	}

	public REASDatos(java.lang.String tipoExpediente,
			java.lang.String idExpediente, java.lang.String fechaExpediente,
			java.lang.String nombreDocumentoRecomendacion,
			java.lang.String fechaDocumentoRecomendacion,
			java.lang.String nombreAdenda, java.lang.String fechaAdenda,
			java.lang.String numeroRadicadoRecomendacion,
			java.lang.String fechaRadicadoRecomendacion,
			java.lang.String remitente, java.lang.String proyecto,
			java.lang.String tipoAmenaza) {
		this.tipoExpediente = tipoExpediente;
		this.idExpediente = idExpediente;
		this.fechaExpediente = fechaExpediente;
		this.nombreDocumentoRecomendacion = nombreDocumentoRecomendacion;
		this.fechaDocumentoRecomendacion = fechaDocumentoRecomendacion;
		this.nombreAdenda = nombreAdenda;
		this.fechaAdenda = fechaAdenda;
		this.numeroRadicadoRecomendacion = numeroRadicadoRecomendacion;
		this.fechaRadicadoRecomendacion = fechaRadicadoRecomendacion;
		this.remitente = remitente;
		this.proyecto = proyecto;
		this.tipoAmenaza = tipoAmenaza;
	}

}